global using Xunit;
global using Moq;
global using Application.Identity;
global using Domain;
global using System.Text.Json;
global using AutoMapper;
global using Application.Interfaces;
global using Application.Tests.Implementations;
global using FluentAssertions;
