import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {AppHeader} from '../components/server/layout/app-header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppHeader></AppHeader>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
