# Name of workflow as seen in Github actions tab
name: aws-concepts-ui-deploy-task
# Run workflow only on push to main branch
on:
  workflow_call:
    inputs:
      target-bucket-name:
        description: 's3 bucket to deploy ui'
        required: true
        type: string
      target-environment-name:
        description: 'nave of environment from where env file will be picked up'
        required: true
        type: string
      aws-region-name:
        description: 'aws region to deploy infrastructure'
        type: string
        default: 'us-east-1'     
    secrets:
      role-to-assume: 
        required: true
      role-session-name: 
        required: true
jobs:
  # To build the project
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Workloads/AwsConceptsApp/ui'
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: replace environment file
        run: |
          content=$(cat ../../../Infrastructure/AwsConceptsApp/Environments/${{ inputs.target-environment-name  }}/Ui.env)
          echo "$content" > .env
      - name: Installing dependencies
        run: npm install
      - name: Building project
        env:
          NODE_OPTIONS: "--max_old_space_size=6096"
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{inputs.aws-region-name}}
          role-to-assume: ${{secrets.role-to-assume}}
          role-session-name: ${{secrets.role-session-name}}

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ ${{ inputs.target-bucket-name  }} --delete
