name: 'aws-concepts-app-infra-deploy'

on:
  push:
    paths:
      - "Infrastructure/AwsConceptsApp/**"
      - ".github/workflows/aws-concepts-app-infra-deploy.yml"
  workflow_dispatch :
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
# Deploy to dev
  call-workflow-terraform-deploy-dev:
    uses: ./.github/workflows/aws-concepts-app-infra-deploy-task.yml
    with:
      environment-name: dev
    secrets:
      role-to-assume: arn:aws:iam::463216347886:role/awsc-github-role
      role-session-name: awsc-github-role
# # Deploy to prod
#   call-workflow-terraform-deploy-prod:
#     needs: call-workflow-terraform-deploy-dev
#     uses: ./.github/workflows/aws-concepts-app-infra-deploy-task.yml
#     with:
#       environment-name: prod
#     secrets: 
#       role-to-assume: arn:aws:iam::788371085266:role/awsc-github-role
#       role-session-name: awsc-github-role
 
